### ISSUE TITLE
Needs improved documentation

### ISSUE THREAD

**Issue by westonganger** [storuky/oxymoron#4]
I really like what this repo has to offer however some better documentation would serve the project well. 

The readme should start with a basic description of what it is and what it does with bullet points of the features it implements.

Also right now it kind of seems like a black box. I had to dig through the code to see whats it is all about. I see there are many unexplained directives, sign in functionality, etc. Some explanation of all of these items would really promote use of this.

**Comment by storuky** [comment]
Good call, @westonganger. I'll try to structure it this weekend.

**Comment by storuky** [comment]
[Done](http://storuky.github.io/oxymoron/)
Let me know if you have questions or feedback.

**Comment by westonganger** [comment]
Oh man that's good stuff.  Now I can get on board with this. My only comment is I can't really read the documentation on my phone because the side nav doesn't have a toggle button to hide/collapse it.

**Comment by storuky** [comment]
@westonganger, check it now:)

**Comment by westonganger** [comment]
Beauty! I think you've improved this a lot this weekend. Thanks for all your hard work for this.
